apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: minikube-01
        url: https://kubernetes.default.svc
        namespace: default
  template:
    metadata:
      name: '{{cluster}}-cloud-services'
    spec:
      project: default
      source:
        repoURL: https://github.com/qtekk/argocdtest
        targetRevision: HEAD
        path: cloud-services
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
