apiVersion: v1
kind: Namespace
metadata:
  name: cloud-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
