repoURL: https://github.com/qtekk/argocdtest
destination:
  server: https://kubernetes.default.svc
project: test-cloud-services
env: test
app: cloud-services

apps:
  - name: strimzi-kafka
    namespace: kafka
    chart:
      repoURL: https://strimzi.io/charts/
      targetRevision: 0.34.0
      name: strimzi-kafka-operator
      values:
        targetRevision: main
        paths:
          - global/values/strimzi-kafka.yml
          - cloud-services/values/strimzi-kafka.yml

  - name: namespaces
    namespace: argocd
    manifest:
      targetRevision: main
      path: cloud-services/manifests/namespaces

  - name: eck-operator
    namespace: monitoring
    chart:
      repoURL: https://helm.elastic.co
      targetRevision: 2.9.0
      name: eck-operator


